/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_M4d5s9hHx",
    "aws_user_pools_web_client_id": "3mmvanl7p5ijdk10f8j9hcvomd",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL",
        "PREFERRED_USERNAME"
    ],
    "aws_content_delivery_bucket": "cw-reactjs-dev-cli-staging",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://cw-reactjs-dev-cli-staging.s3-website.eu-central-1.amazonaws.com"
};


export default awsmobile;
